import Head from "next/head";
import { Navbar } from "../components/navbar";
import Link from "next/link";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>SMKN 2 PKU - Informatics Engineering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      {/* Hero Section */}
      <section className="bg-bottom bg-[url('/bg-hero.jpg')] bg-cover h-screen text-ijo flex lg:items-end items-center">
        <div className="py-8 px-4 max-w-screen-xl lg:py-16 px-20">
          <a href="#" className="inline-flex justify-between items-center py-1 px-1 pr-4 mb-7 text-sm bg-gray-100 rounded-full hover:bg-gray-200" role="alert">
            <span className="text-xs bg-ijo rounded-full text-center lg:text-left text-white px-5 py-1.5 mr-3">New</span> <span className="text-sm font-medium">IT SKANDA Website is out! See what's new</span>
            <svg className="ml-2 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fillRule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
            </svg>
          </a>
          <h1 className="mb-4 text-4xl font-bold lg:font-extrabold max-w-2xl text-center lg:text-left tracking-tight leading-none md:text-5xl lg:text-6xl ">We invest in the world’s potential</h1>
          <p className="mb-8 text-lg font-normal text-gray-500 lg:text-xl max-w-lg">Here we focus on markets where technology, innovation, and capital can unlock long-term value and drive economic growth.</p>
          <div className="flex flex-col mb-8 lg:mb-16 space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4">
            <Link href={`/about-us`}>
              <a className="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white rounded-2xl bg-ijo focus:ring-4">
                Learn more
                <svg className="ml-2 -mr-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </a>
            </Link>
          </div>
        </div>
      </section>

      {/* End Hero Section */}

      {/* About Preview Section */}

      {/* End About Preview Section */}

      {/* Footer Section */}
      <Footer />
      {/* End Footer Section */}
    </>
  );
}
