import Head from "next/head";
// import { Navbar } from "../components/Navbar";

export default function Prestasi() {
  return (
    <>
      <Head>
        <title>Prestasi | SMKN 2 PKU - Informatics Engineering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}
    </>
  );
}
